image:
  file: .gitpod.dockerfile

tasks:
  - before: >
      source ~/.bashrc
    init: |
      echo "Wait for the installation"
      bash /workspace/gitpod-flutter/fonts.sh
      yes | sdk i java 8.0.242-open
      sdk use java 8.0.242-open
      sdk i kotlin
      sdkmanager --update
      yes | sdkmanager --licenses
      flutter pub get
      echo "Ready!"
      echo "running flutter web project..."
      flutter run --web-port=8080
    command: |
      echo "Ready!"
      flutter run --web-port=8080


ports:
  - port: 8080
    onOpen: open-preview
  - port: 5037
    onOpen: ignore
vscode:
  extensions:
    - Nash.awesome-flutter-snippets@2.0.3:6jLJSOqEGV5k8R0xYG7Oqg==
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==
    - Dart-Code.flutter@3.8.1:cytqQi/+kpu802ZOaJwayw==
    - Dart-Code.dart-code@3.8.1:+5Rq24Mq46eJa5w39WY0bA==
    - PKief.material-icon-theme@3.9.3:GVmljEI1+vB8Qkqq/e1dfw==
    - Equinusocio.vsc-material-theme@32.5.0:QKQzJamqCIUjkJSSXc5o8w==
    - alexisvt.flutter-snippets@2.0.0:IZ1TjU5xgx/l/7naPOooFA==
    - rokoroku.vscode-theme-darcula@1.2.0:ZyVHS8l8L8mQegxVPLtifg==
